### PR TITLE
add LD_LIBRARY_PATH to LKM & minimum length of env

### PR DESCRIPTION
**Pull request by chriskaliX**
尝试写了一些 LD_LIBRARY_PATH 的修改，基本照搬。 README 相关还没有做变更

### CODE REVIEW

**Comment by chriskaliX** [comment]
size的范围也要修改一下，我先mark一下

**Review by shenping-bd — COMMENTED** [review]
1 issue to be corrected: should add an extra format "%s RS" for string serializing of ld_library_path, check  PE_printk(...)

Since it changes the trace buffer format, so the change must be synced to agent (user mode). This request will be pended until the agent side is ready. @zhanglei.sec

**Comment by chriskaliX** [comment]
It's done. BTW, I change `if (len > 14 && len < 256)`  to `if (len > 10 && len < 256)`  to avoid env like 'LD_PRELOAD=/1'. Should I change this to 11 or it is fine with 10

**Comment by chriskaliX** [comment]
Agree. I'll do the modification

**Comment by chriskaliX** [comment]
Done, also for the ld_library_path

**Comment by shenping-bd** [comment]
Will be merged to Elkeid v1.8.

**Pull request closed without merging**
